version: "3.7"

services:
  app:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      ACCESS_TOKEN_SECRET: very secret key
      REFRESH_TOKEN_SECRET: very secret key
      HOST_NAME: localhost
      PORT: 4000
      MONGO_URI: mongodb+srv://anhquoc:QuocAnh-1809@cluster0-anhquocdev.6ywog32.mongodb.net/Quizzes?retryWrites=true&w=majority&appName=Cluster0-AnhQuocDev
      LOG_FORMAT: dev
      LOG_DIR: ../logs
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
